require("mgrange.config.conf_nvim-lspconfig")
require("mgrange.config.conf_colors")
require("mgrange.config.conf_completion")
require("mgrange.config.conf_fugitive")
require("mgrange.config.conf_harpoon")
require("mgrange.config.conf_lualine")
require("mgrange.config.conf_neotree")
require("mgrange.config.conf_telescope")
require("mgrange.config.conf_rust-tools")
require("mgrange.config.conf_which-key")
require("mgrange.config.conf_treesitter")

-- require("mgrange.config.conf_lspzero")
-- require("mgrange.config.conf_bufferline")
-- require("mgrange.config.conf_lazygit")
-- require("mgrange.config.conf_comment")
