#  _    _ _   _                           __
# | |  (_) | | |                         / _|
# | | ___| |_| |_ _   _   ___ ___  _ __ | |_
# | |/ / | __| __| | | | / __/ _ \| '_ \|  _|
# |   <| | |_| |_| |_| || (_| (_) | | | | |
# |_|\_\_|\__|\__|\__, (_)___\___/|_| |_|_|
#                  __/ |
#                 |___/

# BEGIN_KITTY_FONTS
# font_family       CaskaydiaCove Nerd Font
# font_family       CaskaydiaMono Nerd Font
# font_family       Hasklug Nerd Font
# font_family       D2CodingLigature Nerd Font
font_family       FiraCode Nerd Font Regular
font_features     FiraCodeNF-Reg +ss02 +ss03 +ss04 +ss05 + ss09 +cv01 +cv02
disable_ligatures never
bold_font         auto
italic_font       auto
bold_italic_font  auto
font_size         9.0
# END_KITTY_FONTS

#BEGIN_KITTY_TABS
tab_bar_edge top
tab_bar_margin_width 0.0
tab_bar_margin_height 0.0 0.0
tab_bar_style fade
tab_bar_min_tabs 2
tab_switch_strategy previous
tab_fade 0.5
tab_title_template "{fmt.fg.tab}{title}"
#END_KITTY_TABS

# BEGIN_KITTY_COLORS
background #262335
foreground #E0D9F5

color0     #262335
color1     #FE4450
color2     #72F1B8
color3     #FEDE5D
color4     #36F9F6
color5     #B893CE
color6     #FF7EDB
color7     #E0D9F5
color8     #6C6783
color9     #FE6973
color10    #8EF3C6
color11    #FEE47D
color12    #5EFAF7
color13    #C6A8D7
color14    #FF97E2
color15    #E6E0F7

background_opacity 0.8
# END_KITTY_COLORS

# BEGIN_KITTY_MISC
window_padding_width 20
hide_window_decorations yes
allow_hyperlinks yes
clipboard_control write-clipboard write-primary no-append
# END_KITTY_MISC
