#  _    _ _   _                           __
# | |  (_) | | |                         / _|
# | | ___| |_| |_ _   _   ___ ___  _ __ | |_
# | |/ / | __| __| | | | / __/ _ \| '_ \|  _|
# |   <| | |_| |_| |_| || (_| (_) | | | | |
# |_|\_\_|\__|\__|\__, (_)___\___/|_| |_|_|
#                  __/ |
#                 |___/

# BEGIN_KITTY_FONTS
# font_family       CaskaydiaCove Nerd Font
# font_family       CaskaydiaMono Nerd Font
# font_family       Hasklug Nerd Font
# font_family       D2CodingLigature Nerd Font
font_family       FiraCode Nerd Font
# cv01: Alternate a
# cv02: Alternate g
# ss02: Alternate <= >=
# ss03: Alternate &
# ss04: Alternate $
# ss05: Alternate @
# ss09: Alternate >>= <<=
font_features     FiraCodeNF-Reg +ss02 +ss03 +ss04 +ss09
disable_ligatures never
bold_font         auto
italic_font       auto
bold_italic_font  auto
font_size         9.0
# END_KITTY_FONTS

#BEGIN_KITTY_TABS
tab_bar_edge top
tab_bar_margin_width 0.0
tab_bar_margin_height 0.0 0.0
tab_bar_style fade
tab_bar_min_tabs 2
tab_switch_strategy previous
tab_fade 0.5
tab_title_template "{fmt.fg.tab}{title}"
#END_KITTY_TABS

# BEGIN_KITTY_COLORS
background #282828
foreground #EBDBB2

color0     #282828
color1     #FB4934
color2     #B8BB26
color3     #FABD2F
color4     #83A598
color5     #D3869B
color6     #8EC07C
color7     #EBDBB2
color8     #928374
color9     #FB6D5C
color10    #C6C851
color11    #FBCA58
color12    #9BB7AC
color13    #DB9EAF
color14    #A4CC96
color15    #EFE2C1

background_opacity 0.8
# END_KITTY_COLORS

# BEGIN_KITTY_MARKS
mark1_background #44415A
mark1_foreground #FE6973
mark2_background #44415A
mark2_foreground #FEE47D
mark3_background #44415A
mark3_foreground #8EF3C6
map f1 toggle_marker iregex 1 \\berr\\b|\\b\\w*error\\w*\\b|\\[error\\]|\\[!\\]|\\bfail\\b|\\bfailure\\b|\\boffline\\b 2 \\b\\w*warn\\w*\\b|\\[\\*\\] 3 \\bok\\b|\\[ok\\]|\\b\\w*success\\w*\\b|\\bgood\\b|\\bonline\\b|\\b\\w*pass\\w*\\b|\\[\\+\\]
# END_KITTY_MARKS

# BEGIN_KITTY_MISC
window_padding_width 10
hide_window_decorations yes
allow_hyperlinks yes
clipboard_control write-clipboard write-primary no-append
# END_KITTY_MISC
