# i3status configuration file.
# see "man i3status" for documentation.

# It is important that this file is edited as UTF-8.
# The following line should contain a sharp s:
# ß
# If the above line is not correctly displayed, fix your editor first!

general {
        output_format = "i3bar"
        colors = true
        color_good = "#72f1b8"
        color_degraded = "#b893ce"
        color_bad = "#fe4450"
        interval = 5
}

# order += "ipv6"
# order += "wireless _first_"
order += "ethernet _first_"
order += "cpu_usage"
order += "cpu_temperature 0"
order += "load"
order += "disk /"
order += "memory"
order += "volume master"
order += "tztime local"
# order += "read_file UPTIME"

# wireless _first_ {
#         format_up = "W: (%quality at %essid) %ip"
#         format_down = "W: down"
# }

ethernet _first_ {
        format_up = "Ethernet: [ IP: %ip Speed: %speed ]"
        format_down = "Ethernet: [ down ]"
}

# battery all {
#         format = "%status %percentage %remaining"
# }

cpu_usage {
        format = "CPU: [ %usage ]"
}

cpu_temperature 0 {
        format = "Temp: [ %degrees °C ]"
}

load {
        format = "Load: [ %1min ]"
}


disk "/" {
        format = "Disk: [ %percentage_used (%free %avail/%total) ]"
}

memory {
        format = "Memory: [ %percentage_used (%used / %available) ]"
        threshold_degraded = "1G"
        format_degraded = "MEMORY: [ !! < %available !!]"
}

volume master {
        format = "♪: [ %volume ]"
        format_muted = "♪: [ muted (%volume) ]"
        device = "default"
        mixer = "Master"
        mixer_idx = 0
}

tztime local {
        format = "Date: [ %Y-%m-%d ] // Time: [ %H:%M ]"
}

# read_file UPTIME {
#         format = "%title: [ %content ]"
#         path = "/proc/uptime"
# }
